version: "3"

services:
  server:
    container_name: yspotify_server
    image: yooooomi/your_spotify_server
    restart: unless-stopped
    ports:
      - 7000:8080
    environment:
      - API_ENDPOINT=https://yspotify.tharindur.dev/api
      - CLIENT_ENDPOINT=https://yspotify.tharindur.dev
      - SPOTIFY_PUBLIC=$SPOTIFY_PUBLIC
      - SPOTIFY_SECRET=$SPOTIFY_SECRET
  
  mongo:
    container_name: mongo
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
      - mongo_configdb:/data/configdb
  
  client:
    container_name: yspotify_client
    image: yooooomi/your_spotify_client
    restart: unless-stopped
    ports:
      - 7001:3000
    environment:
      - API_ENDPOINT=https://yspotify.tharindur.dev/api

volumes:
  mongo_data:
  mongo_configdb:
